require File.join('lokii', 'logger')
require File.join('lokii', 'config')
require File.join('lokii', 'server')
require File.join('lokii', 'handler')
require File.join('lokii', 'processor')
require File.join('lokii', 'handlers', 'ping_handler')
require File.join('lokii', 'handlers', 'i_love_you_handler')