#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

LOKII_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
LOKII_ENV = ENV['LOKII_ENV'] || 'development'
LOKII_DAEMON = true

if File.exist?(File.join(LOKII_ROOT, 'lib', 'lokii.rb'))
  $:.unshift(File.join(LOKII_ROOT, 'lib'))
end

require 'lokii'

if ARGV.empty?
  "Usage: lokii [connect|disconnect|start|stop|restart]"
  exit
end

if ARGV[0] == 'connect'
  Lokii::Server.connect
  exit
end

if ARGV[0] == 'disconnect'
  Lokii::Server.disconnect
  exit
end

options = {
  :multiple => false,
  :dir_mode => :normal,
  :dir => File.join(LOKII_ROOT, 'tmp', 'pids'),
  :backtrace => true,
  :log_output => true,
  :app_name => 'lokii'
}
#:monitor => true

Daemons.run(File.join(LOKII_ROOT, 'lib', 'process.rb'), options)