#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

LOKII_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
LOKII_ENV = ENV['LOKII_ENV'] || 'development'
LOKII_DAEMON = true

if File.exist?(File.join(LOKII_ROOT, 'lib', 'lokii.rb'))
  $:.unshift(File.join(LOKII_ROOT, 'lib'))
end

options = {
  :multiple => false,
  :dir_mode => :normal,
  :dir => File.join(LOKII_ROOT, 'tmp', 'pids'),
  :backtrace => true,
  :log_output => true,
  :app_name => 'lokii'
}
#:monitor => true

require 'lokii'
Daemons.run(File.join(LOKII_ROOT, 'lib', 'process.rb'), options)

Lokii::Server.teardown