#!/usr/bin/env ruby
require File.join(File.dirname(__FILE__), '..', 'config', 'boot')

# Check if it is already running
if Lokii::Processor.running?
  Lokii::Logger.debug "Already running, aborting"
  exit
end

File.open(File.join(Lokii::Config.root, Lokii::Config.pid).gsub(File::SEPARATOR, File::ALT_SEPARATOR || File::SEPARATOR), 'w') do |pid|
  pid.write(Process.pid)
end  

trap "SIGINT" do
  Lokii::Logger.debug "Interuppted"
  exit
end

begin
  Lokii::Processor.servers.each{|server| server.connect }  
  require 'process'
ensure
  Lokii::Processor.servers.each{|server| server.disconnect }  
  FileUtils.rm(File.join(Lokii::Config.root, Lokii::Config.pid).gsub(File::SEPARATOR, File::ALT_SEPARATOR || File::SEPARATOR), :force => true)
end  