#!/usr/bin/env ruby
require 'rubygems'

LOKII_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
LOKII_ENV = ENV['LOKII_ENV'] || 'development'

if File.exist?(File.join(LOKII_ROOT, 'config', 'init.rb'))
  $:.unshift(File.join(LOKII_ROOT, 'config'))
end

require 'init'

# Check if it is already running
if Lokii::Processor.running?
  Lokii::Logger.err "Already running, aborting"
  exit
end

File.open(File.join(Lokii::Config.root, Lokii::Config.pid), 'w') do |pid|
  pid.write(Process.pid)
end  

trap "SIGINT" do
  Lokii::Logger.debug "Interuppted"
  exit
end

begin
  Lokii::Processor.servers.each{|server| server.connect }  
  require 'process'
ensure
  Lokii::Processor.servers.each{|server| server.disconnect }  
  FileUtils.rm(File.join(Lokii::Config.root, Lokii::Config.pid), :force => true)
end  