#!/usr/bin/env ruby
require 'rubygems'

LOKII_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
LOKII_ENV = ENV['LOKII_ENV'] || 'development'

if File.exist?(File.join(LOKII_ROOT, 'lib', 'lokii.rb'))
  $:.unshift(File.join(LOKII_ROOT, 'lib'))
end

require 'lokii'

# Check if it is already running
if Lokii::Server.running?
  Lokii::Logger.err "Already running, aborting"
  exit
end

File.open(File.join(Lokii::Config.root, Lokii::Config.pid), 'w') do |pid|
  pid.write(Process.pid)
end  

trap "SIGINT" do
  Lokii::Logger.debug "Interuppted"
  exit
end

begin
  Lokii::Server.connect
  require 'process'
ensure
  Lokii::Server.disconnect
  FileUtils.rm(File.join(Lokii::Config.root, Lokii::Config.pid), :force => true)
end  